"""tipos de ativo

Revision ID: 1cb48ab1f96d
Revises: 275b8f546f21
Create Date: 2026-08-28 01:07:44.852955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb48ab1f96d'
down_revision = '275b8f546f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_type', sa.String(length=20), server_default='investment', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('asset_type')

    # ### end Alembic commands ###
