"""add playlists

Revision ID: 1da1623370fc
Revises: b4c9045f6d1e
Create Date: 2026-08-26 23:25:21.128390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da1623370fc'
down_revision = 'b4c9045f6d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'playlists', ['playlist_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'playlists', ['playlist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('playlist_id')

    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('playlist_id')

    op.drop_table('playlists')
    # ### end Alembic commands ###
