"""recorrente: automatico ou manual

Revision ID: 275b8f546f21
Revises: 6be9aa5d32f5
Create Date: 2026-08-28 00:54:58.491519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275b8f546f21'
down_revision = '6be9aa5d32f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_column('auto')

    # ### end Alembic commands ###
