"""net worth flag and shopping item options

Revision ID: 38ea1afd7aed
Revises: f4e964cf3fc9
Create Date: 2026-08-27 02:10:17.034315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ea1afd7aed'
down_revision = 'f4e964cf3fc9'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'counts_in_net_worth', sa.Boolean(), nullable=False, server_default=sa.true()
            )
        )

    # Ativos guardam valor e contam no patrimônio; playlists são consumo e não contam.
    op.execute("UPDATE playlists SET counts_in_net_worth = (kind = 'asset')")

    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('priority', sa.String(length=20), nullable=False, server_default='medium')
        )
        batch_op.add_column(sa.Column('notes', sa.String(length=500), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('priority')

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('counts_in_net_worth')

    # ### end Alembic commands ###
