"""comissao em emprestimos

Revision ID: 8a2557e867b7
Revises: cb9e8d55140b
Create Date: 2026-10-05 23:48:02.840528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2557e867b7'
down_revision = 'cb9e8d55140b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('commission_rate')

    # ### end Alembic commands ###
