"""add opening value to playlists

Revision ID: ab85ba73359f
Revises: 38ea1afd7aed
Create Date: 2026-08-27 02:23:36.157020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab85ba73359f'
down_revision = '38ea1afd7aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'opening_value',
                sa.Numeric(precision=12, scale=2),
                nullable=False,
                server_default='0',
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('opening_value')

    # ### end Alembic commands ###
