"""adiamento de recorrente

Revision ID: cb9e8d55140b
Revises: ebdd5e0de228
Create Date: 2026-10-05 22:34:47.708597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9e8d55140b'
down_revision = 'ebdd5e0de228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postponed_until', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_column('postponed_until')

    # ### end Alembic commands ###
