"""add auto_source to playlists

Revision ID: eb96c51bbc09
Revises: c859564ab750
Create Date: 2026-08-27 03:43:18.114587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb96c51bbc09'
down_revision = 'c859564ab750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_source', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('auto_source')

    # ### end Alembic commands ###
