"""moeda por posicao e metas

Revision ID: ebdd5e0de228
Revises: 1cb48ab1f96d
Create Date: 2026-10-05 22:16:53.125393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebdd5e0de228'
down_revision = '1cb48ab1f96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), server_default='BRL', nullable=False))
        batch_op.alter_column('opening_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))

    with op.batch_alter_table('snapshot_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('native_value', sa.Numeric(precision=18, scale=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot_entries', schema=None) as batch_op:
        batch_op.drop_column('native_value')

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.alter_column('opening_value',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.drop_column('currency')

    op.drop_table('goals')
    # ### end Alembic commands ###
